config/routes.rb
Rails.application.routes.draw do
  get 'reservations/index'
  devise_for :users
  get '/', to: 'home#top'
  resources :rooms
  resources :users, only: [:update]
  get 'users/account', to: 'users#account'
  get 'users/profile', to: 'users#profile'
  resources :reservations
  get 'search', to: 'rooms#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    has_many :reservation, dependent: :destroy

    validates :name, presence: true
    validates :introduction, presence: true
    validates :price, presence: true, numericality: true
    validates :address, presence: true
    validates :image, presence: true, blob: { content_type: :image } 
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find(params[:id])
    @user_id = current_user.id
    @user_image = @room.user.image
    @reservation = Reservation.new
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new(rooms_params)
    @room.user_id = current_user.id
    if @room.save
      flash[:notice] = "ルームを登録しました。"
      redirect_to room_path(@room)
    else
      render "new"
    end
  end

  def search
    if params[:keyword] == '' || nil
      @searchs = Room.all
    else
      @searchs = Room.where('name LIKE ? OR introduction LIKE ? OR address LIKE ?','%'+params[:keyword]+'%','%'+params[:keyword]+'%','%'+params[:keyword]+'%' )
    end
  end

  private

  def rooms_params
    params.require(:room).permit(
      :name, :introduction, :price, :address, :image, :user_id
    )
  end
end

app/views/rooms/index.html.erb
<div class="rooms-container">
    <h4>登録済みルーム一覧</h4>
    <table class="rooms-table" style="border-collapse: collapse">
        <thead>
            <tr>
                <th>ルーム画像</th>
                <th>ルーム名</th>
                <th>ルーム紹介</th>
                <th>料金</th>
                <th>作成日</th>
            </tr>
        </thead>
        <tbody>
            <% @rooms.each do |room| %>
                <tr>
                    <td class="room-image"><%= link_to image_tag(room.image), room_path(room) %></td>
                    <td class="room-name"><%= link_to room.name, room_path(room) %></td>
                    <td class="room-content"><%= room.introduction %></td>
                    <td class="room-price"><%= room.price %></td>
                    <td class="room-create-day"><%= room.created_at.to_s(:datetime_jp) %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/rooms/new.html.erb
<div class="user-container">
    <div class="user-nav">
        <ul>
            <li class="user-view-active-li"><%= link_to "基本情報", new_room_path, class: 'user-view-active-a'%></li>
        </ul>
    </div>
    
    <div class="user-view">
        <%= render "shared/error", obj: @room %> 
        <div class="user-view-box">
            <h6 class="user-view-title">ルーム情報登録</h6>
            <%= form_with model:@room do |f| %>
                <table>
                    <tr>
                        <th><%= f.label :name, "ルーム名", class: 'form-require-after' %></th>
                        <td><%= f.text_field :name, placeholder: "ルーム名を入力" %></td>
                    </tr>
                    <tr>
                        <th><%= f.label :introduction, "ルーム紹介", class: 'form-require-after' %></th>
                        <td><%= f.text_area :introduction, placeholder: "ルーム説明を入力" %></td>
                    </tr>
                    <tr>
                        <th><%= f.label :price, "料金", class: 'form-require-after' %></th>
                        <td><%= f.text_field :price, placeholder: "一日あたりの料金を入力" %></td>
                    </tr>
                    <tr>
                        <th><%= f.label :address, "住所", class: 'form-require-after' %></th>
                        <td><%= f.text_field :address, placeholder: "住所を入力" %></td>
                    </tr>
                    <tr>
                        <th><%= f.label :image, "ルーム画像", class: 'form-require-after' %></th>
                        <td><%= f.file_field :image %></td>
                    </tr>
                </table>
                <ul class="user-view-btn">
                    <li><%= f.submit "登録" %></li>
                </ul>
            <% end %>
        </div>
    </div>
</div>

app/views/rooms/search.html.erb
<div class="room-search-container">
    <h4>検索結果：<%= @searchs.count %>件</h4>
    
    <div class="room-search-row">
    <% @searchs.each do |search| %>
        <div class="room-frame">
            
                <div class="room-frame-inner">
                    <%= link_to room_path(search.id) do %>
                    <div class="room-frame-inner-image">
                        <%= image_tag(search.image) %>
                    </div>
                    <div class="room-profile">
                        <p class="room-profile-name"><%= search.name %></p>
                        <p class="room-profile-address"><%= search.address %></p>
                        <p class="room-profile-price"><%= search.price %>円</p>
                    </div>
                </div>
                <% end %>
            </div>
        <% end %>
    </div>
</div>

app/views/rooms/show.html.erb
<div class="container">
    <%= render "shared/error", obj: @reservation %>
    <div class="room-show-box">
        <div class="room-information">
            <%= image_tag(rails_blob_path(@room.image)) %>
            <div class="room-content-detail">
                <%if @user_image.attached? %>
                    <%= image_tag(rails_blob_path(@user_image), class: 'icon-img') %>
                <% else %>
                    <img alt="アイコン画像", class="icon-img" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg">
                <% end %>
                <div class="room-detail-profile">
                    <p class="room-show-profile-name"><%= @room.name %></p>
                    <p class="room-show-profile-address"><%= @room.address %></p>
                </div>
            </div>
            <p class="room-introduction"><%= @room.introduction %></p>
        </div>
        <div class="room-reserve-box">
            <div class="room-reserve-detail">
                <h5 class="price-icon"><%= @room.price %> / 日</h5>
                <div class="room-reserve-detail-select">
                    <%= form_with model: @reservation, method: :get, url: new_reservation_path do |f| %>

                        <%= f.hidden_field :user_id, value: @user_id %>
                        <%= f.hidden_field :room_id, value: @room.id %>

                        <%= f.label :start_date, "開始日" %>
                        <%= f.date_field :start_date, placeholder: "年/月/日" %>

                        <%= f.label :end_date, "終了日" %>
                        <%= f.date_field :end_date, placeholder: "年/月/日" %>
                        
                        <%= f.label :num_people, "人数" %>
                        <%= f.number_field :num_people %>

                        <ul class="user-view-btn">
                            <li><%= f.submit "予約する" %></li>
                        </ul>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>