config/routes.rb
Rails.application.routes.draw do
  get 'reservations/index'
  devise_for :users
  get '/', to: 'home#top'
  resources :rooms
  resources :users, only: [:update]
  get 'users/account', to: 'users#account'
  get 'users/profile', to: 'users#profile'
  resources :reservations
  get 'search', to: 'rooms#search'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header>
      <div class="header-container">
        <div class="left-nav">
          <a href="/">
            <img alt="サイトのロゴ画像" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png">
          </a>
          <%= form_with url: search_path, method: :get, local: true do |f| %>
            <%= f.text_field :keyword, placeholder: "キーワード" %>
            <%= f.submit "検索" %>
          <% end %>
        </div>
        <div class="right-nav">
          <% if user_signed_in? %>
            <p><%= current_user.name %></p>
            <%if current_user.image.attached? %>
              <%= image_tag(rails_blob_path(current_user.image), id: 'host-icon', class: 'icon-img') %>
            <% else %>
              <img alt="アイコン画像", id="host-icon", class="icon-img", src="https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg">
            <% end %>
            <ul id="header-nav-menu" class="hiddn">
              <li><%= link_to "ルーム登録", new_room_path %></li>
              <li><%= link_to "予約済みルーム一覧", reservations_path %></li>
              <li><%= link_to "登録済みルーム一覧", rooms_path %></li>
              <li><%= link_to "設定", users_account_path %></li>
              <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
            </ul>
          <% else %>
            <%= link_to "ログイン", new_user_session_path, class: 'btn right-nav-login' %>
            <%= link_to "登録する", new_user_registration_path, class: 'btn right-nav-registration' %>
          <% end %>
        </div>
      </div>
    </header>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
    <%= yield %>
    <footer>
      <p>© 2020 POTEPAN.INC.</p>
    </footer>
  </body>
</html>